preferred_syntax = :sass
http_path = '/'
css_dir = ''
sass_dir = 'scss/'
images_dir = 'assets/images'
javascripts_dir = 'assets/javascripts'
relative_assets = true
line_comments = true
# output_style = :compressed